const safeFoodData = [
    {
        'id': 1,
        'pet': 'Dog',
        'description': 'Omnivores',
        'nutrition': 'Dogs enjoy a variety in their diet',
        'safeFruits': [
            'apple',
            'banana',
            'blueberries',
            'cantaloupe',
            'cranberries',
            'cucumbers',
            'mango',
            'peach',
            'oranges',
            'pears',
            'pineapple',
            'pumpkin',
            'raspberries',
            'strawberries',
            'watermelon'
        ],
        'avoidFruits': [
            'avocado',
            'CHERRIES',
            'GRAPES',
            'tomato',
        ],
        'safeVeggies': [
            'broccoli',
            'brussel sprouts',
            'carrots',
            'celery',
            'green beans',
            'peas',
            'spinach',
            'cabbage'
        ],
        'avoidVeggies': [
            'MUSHROOMS',
            'asparagus',
            'ONIONS'
        ],
        'otherSafe': [
            'bread',
            'cashews (unsalted)',
            'cheese',
            'coconut',
            'corn (off the cob)',
            'eggs (cooked)',
            'fish',
            'ham',
            'honey',
            'milk',
            'peanut butter',
            'peanuts',
            'popcorn',
            'pork',
            'quinoa',
            'salmon (fully cooked)',
            'shrimp (fully cooked)',
            'tuna',
            'turkey',
            'wheat/grains',
            'yogurt (no artificial sweeteners)'

        ],
        'otherAvoid': [
            'almonds',
            'CHOCOLATE (especially DARK)',
            'cinnamon',
            'GARLIC',
            'ice cream',
        ]
    }, 
    {
        'id': 2,
        'pet': 'Cat',
        'description': 'Carnivores',
        'nutrition': 'Cats are typically fond of wet food',
        'safeFruits': [
            'apples',
            'bananas',
            'blueberries',
            'pears',
            'strawberries',
            'raspberries',
            'cranberries',
            'watermelon',
            'pineapple',
            'pumpkin',
            'cantaloupe',
            'honeydew'
        ],
        'avoidFruits': [
            'GRAPES',
            'RAISINS',
            'ORANGES',
            'avocado',
            'peaches (pit is TOXIC)',
            'CHERRIES',
            'PLUMS',
            'tomatoes (skin is TOXIC)'
        ],
        'safeVeggies': [
            'carrots (cooked)',
            'cucumbers',
            'celery',
            'green beans',
            'potato (boiled or baked)',
            'spinach (not for digestive issues)',
            'lettuce'
        ],
        'avoidVeggies': [
            'broccoli (boiled; with caution)',
            'corn',
            'ONION',
            'GARLIC',
            'mushroom (NO WILD)'
        ],
        'otherSafe': [
            'fish (boiled is actually very healthy, avoid bones)',
            'shrimp',
            'bacon',
            'ham',
            'eggs (fully cooked)',
            'oatmeal (very beneficial for allergies and coat',
            'tuna fish',
            'bread',
            'rice'
        ],
        'otherAvoid': [
            'peanut butter',
            'raw meat',
            'BONES',
            'MILK',
            'cheese',
            'ice cream',
            'yogurt',
            'nuts',
            'popcorn',
            'CHOCOLATE (sugar-free; DARK)'
        ]
    },
    {
        'id': 3,
        'pet': 'Hamster / Gerbil',
        'description': 'Omnivore',
        'nutrition': 'Hamsters and Gerbils are both omnivores, meaning they can eat both animal and plant material! Providing your hamster or gerbil with different treats is a fun way to bond with your pet and create a good and healthy relationship! With that said, these treats should never substitute your rodents diet, and should only be about 5% of their daily food intake. Many FRUITS are high in sugar and should be fed in VERY SMALL amounts. Foods that are CAPTILIZED should never be fed to your hamster or gerbil, and can cause serious illness. Others in the "avoid" category are technically safe to eat, but in extreme moderation, or not at all.',
        'safeFruits': [
            'apple (skinned)',
            'banana',
            'sweet potato',
            'pears',
            'blueberries',
            'strawberries',
            'plums',
            'coconut',
            'figs',
            'grapes (half)',
            'kiwi fruit',
            'mango',
            'peach',
            'melon',
            'watermelon'
        ],
        'avoidFruits': [
            'APPLE SEEDS',
            'tomato'
        ],
        'safeVeggies': [
            'cucumbers',
            'carrots',
            'spinach',
            'squash',
            'pumpkin',
            'green beans',
            'peas'
        ],
        'avoidVeggies': [
            'UNWASHED VEGGIES',
            'sweet peppers',
            'potato'
        ],
        'otherSafe': [
            'mealworms',
            'crickets',
            'boiled eggs',
            'plain tofu',
            'timothy hay',
            'low-fat yogurt',
            'low-fat cottage cheese'
        ],
        'otherAvoid': [
            'CHOCOLATE',
            'ALMONDS',
            'citrus fruits',
            'pork',
            'beef',
            'rhubarb leaves/ raw rhubarb',
            'PEANUTS'

        ]
    },
    {
        'id': 4,
        'pet': 'Rabbits',
        'description': 'Herbivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 5,
        'pet': 'Rats / Mice',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 6,
        'pet': 'Guinea Pigs',
        'description': 'Herbivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 7,
        'pet': 'Ferrets',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 8,
        'pet': 'Hedgehog',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 9,
        'pet': 'Chinchilla',
        'description': 'Herbivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 10,
        'pet': 'Sugar Glider',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 11,
        'pet': 'Bearded Dragon',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 12,
        'pet': 'Box Turtle',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 13,
        'pet': 'Chameleon',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 14,
        'pet': 'Snake',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 15,
        'pet': 'Green Iguana',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 16,
        'pet': 'Blue Tongue Skinks',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 17,
        'pet': 'Budgie (Parakeet)',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 18,
        'pet': 'Cockatiel',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 19,
        'pet': 'Grey Parrot',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 20,
        'pet': 'Conures',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 21,
        'pet': 'Canary',
        'description': 'Omnivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 22,
        'pet': 'Goldfish',
        'description': 'Herbivore',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    },
    {
        'id': 23,
        'pet': 'Freshwater Fish',
        'description': 'Herbi',
        'nutrition': '',
        'safeFruits': [],
        'avoidFruits': [],
        'safeVeggies': [],
        'avoidVeggies': [],
        'otherSafe': [],
        'otherAvoid': []
    }
]

export default safeFoodData 